services:

  backend:
    image: docker.io/library/php:8.4-apache-bookworm
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/html
        read_only: true
    # ports:
    #   - "80:80"
    # env_file: "./.env.production.local"
    restart: always
